#ifndef GLOBAL_H
#define GLOBAL_H

enum STATE{LOADING, LOGIN, CHECKINGLOGIN, MENU, ABOUT, LOADSERVERLIST, SERVERLIST, CONNECTINIT, CONNECTING, GAME, DISCONNECT, CLOSE};

const int ScreenHeight = 600;
const int ScreenWidth = 800;

#endif // GLOBAL_H
