#############################################################################
# Makefile for building: tis
# Generated by qmake (3.0) (Qt 5.0.2) on: Tue Feb 4 23:36:19 2014
# Project:  tis.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile tis.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-netlib \
		sub-server \
		sub-client


sub-netlib-qmake_all:  FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile
	cd netlib/ && $(MAKE) -f Makefile qmake_all
sub-netlib: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile
sub-netlib-make_first-ordered: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-netlib-make_first: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-netlib-all-ordered: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-netlib-all: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-netlib-clean-ordered: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-netlib-clean: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-netlib-distclean-ordered: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-netlib-distclean: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-netlib-install_subtargets-ordered: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-netlib-install_subtargets: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-netlib-uninstall_subtargets-ordered: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-netlib-uninstall_subtargets: FORCE
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-server-qmake_all: sub-netlib-qmake_all FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile
	cd server/ && $(MAKE) -f Makefile qmake_all
sub-server: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile
sub-server-make_first-ordered: sub-netlib-make_first-ordered  FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-server-make_first: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-server-all-ordered: sub-netlib-all-ordered  FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-server-all: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-server-clean-ordered: sub-netlib-clean-ordered  FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-server-clean: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-server-distclean-ordered: sub-netlib-distclean-ordered  FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-server-distclean: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-server-install_subtargets-ordered: sub-netlib-install_subtargets-ordered  FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-server-install_subtargets: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-server-uninstall_subtargets-ordered: sub-netlib-uninstall_subtargets-ordered  FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-server-uninstall_subtargets: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-client-qmake_all: sub-server-qmake_all FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile
	cd client/ && $(MAKE) -f Makefile qmake_all
sub-client: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile
sub-client-make_first-ordered: sub-server-make_first-ordered  FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-client-make_first: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-client-all-ordered: sub-server-all-ordered  FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-client-all: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-client-clean-ordered: sub-server-clean-ordered  FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-client-clean: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-client-distclean-ordered: sub-server-distclean-ordered  FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-client-distclean: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-client-install_subtargets-ordered: sub-server-install_subtargets-ordered  FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-client-install_subtargets: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-client-uninstall_subtargets-ordered: sub-server-uninstall_subtargets-ordered  FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-client-uninstall_subtargets: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: tis.pro /usr/share/qt5/mkspecs/linux-g++-64/qmake.conf /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/shell-unix.conf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/unix/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		tis.pro
	$(QMAKE) -o Makefile tis.pro
/usr/share/qt5/mkspecs/features/spec_pre.prf:
/usr/share/qt5/mkspecs/common/shell-unix.conf:
/usr/share/qt5/mkspecs/common/unix.conf:
/usr/share/qt5/mkspecs/common/linux.conf:
/usr/share/qt5/mkspecs/common/gcc-base.conf:
/usr/share/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt5/mkspecs/common/g++-base.conf:
/usr/share/qt5/mkspecs/common/g++-unix.conf:
/usr/share/qt5/mkspecs/qconfig.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_bootstrap.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmldevtools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/share/qt5/mkspecs/features/qt_functions.prf:
/usr/share/qt5/mkspecs/features/qt_config.prf:
/usr/share/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/share/qt5/mkspecs/features/spec_post.prf:
/usr/share/qt5/mkspecs/features/exclusive_builds.prf:
/usr/share/qt5/mkspecs/features/default_pre.prf:
/usr/share/qt5/mkspecs/features/unix/default_pre.prf:
/usr/share/qt5/mkspecs/features/resolve_config.prf:
/usr/share/qt5/mkspecs/features/default_post.prf:
/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt5/mkspecs/features/warn_on.prf:
/usr/share/qt5/mkspecs/features/wayland-scanner.prf:
/usr/share/qt5/mkspecs/features/testcase_targets.prf:
/usr/share/qt5/mkspecs/features/exceptions.prf:
/usr/share/qt5/mkspecs/features/yacc.prf:
/usr/share/qt5/mkspecs/features/lex.prf:
tis.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile tis.pro

qmake_all: sub-netlib-qmake_all sub-server-qmake_all sub-client-qmake_all FORCE

make_first: sub-netlib-make_first-ordered sub-server-make_first-ordered sub-client-make_first-ordered FORCE
all: sub-netlib-all-ordered sub-server-all-ordered sub-client-all-ordered FORCE
clean: sub-netlib-clean-ordered sub-server-clean-ordered sub-client-clean-ordered FORCE
distclean: sub-netlib-distclean-ordered sub-server-distclean-ordered sub-client-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-netlib-install_subtargets-ordered sub-server-install_subtargets-ordered sub-client-install_subtargets-ordered FORCE
uninstall_subtargets: sub-netlib-uninstall_subtargets-ordered sub-server-uninstall_subtargets-ordered sub-client-uninstall_subtargets-ordered FORCE

sub-netlib-check_ordered:
	@test -d netlib/ || mkdir -p netlib/
	cd netlib/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/netlib/netlib.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-server-check_ordered: sub-netlib-check_ordered 
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/server/server.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-client-check_ordered: sub-server-check_ordered 
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) /home/zmattor/Work/tis/client/client.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-netlib-check_ordered sub-server-check_ordered sub-client-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

